### ISSUE TITLE
input newick 

### ISSUE THREAD

**Issue by smirarab** [smirarab/ASTRAL#19]
(from pranjal)

ASTRAL fails on inputs where a single taxon is contained in
 parentheses. Technically these might not be legal newick files but a
 better error message might be nice.

e.g.

$ cat /tmp/astral-test-2

(a, (b), (c, d))

$ java -jar ~/.local/lib/astral.4.10.12.jar -i /tmp/astral-test-2

================== ASTRAL =====================

This is ASTRAL version 4.10.12
Gene trees are treated as unrooted
1 trees read from /tmp/astral-test-2
All output trees will be *arbitrarily* rooted at a

======== Running the main analysis
Number of taxa: 4 (4 species)
Taxa: [a, b, c, d]
Taxon occupancy: {a=1, b=1, c=1, d=1}
Number of gene trees: 1
0 trees have missing taxa
Calculating quartet distance matrix (for completion of X)
Exception in thread "main" java.util.NoSuchElementException
        at java.util.ArrayDeque.removeFirst(java.base@9-Ubuntu/ArrayDeque.java:264)
        at java.util.ArrayDeque.pop(java.base@9-Ubuntu/ArrayDeque.java:499)
        at phylonet.coalescent.SimilarityMatrix.populateByQuartetDistance(SimilarityMatrix.java:139)
        at phylonet.coalescent.WQDataCollection.calculateDistances(WQDataCollection.java:398)
        at phylonet.coalescent.WQDataCollection.computeTreePartitions(WQDataCollection.java:372)
        at phylonet.coalescent.AbstractInference.setupSearchSpace(AbstractInference.java:288)
        at phylonet.coalescent.AbstractInference.setup(AbstractInference.java:269)
        at phylonet.coalescent.CommandLine.runOnOneInput(CommandLine.java:600)
        at phylonet.coalescent.CommandLine.runInference(CommandLine.java:584)
        at phylonet.coalescent.CommandLine.main(CommandLine.java:390)

**Comment by smirarab** [comment]
Fixed in 5.7.6.
