### ISSUE TITLE
-x in MP-Similarity branch

### ISSUE THREAD

**Issue by smirarab** [smirarab/ASTRAL#48]
in MP-Similarity branch, using `-x` gives:

```
Exception in thread "main" java.lang.RuntimeException: Not supported
        at phylonet.util.BitSet$ImmutableBitSet.clear(BitSet.java:67)
        at phylonet.coalescent.AbstractDataCollection.addAllPossibleSubClusters(AbstractDataCollection.java:53)
        at phylonet.coalescent.AbstractInference.setupSearchSpace(AbstractInference.java:326)
        at phylonet.coalescent.AbstractInference.setup(AbstractInference.java:299)
        at phylonet.coalescent.CommandLine.runOnOneInput(CommandLine.java:607)
        at phylonet.coalescent.CommandLine.runInference(CommandLine.java:598)
        at phylonet.coalescent.CommandLine.main(CommandLine.java:508)
```

**Comment by smirarab** [comment]
Issue has been fixed since 5.14.6
