### ISSUE TITLE
Error in running the tool: Input tree error

### ISSUE THREAD

**Issue by Upendra19993** [smirarab/ASTRAL#93]
Hi, 
I want to run Astral for my dataset. But when I execute the command, I am getting this error.

This is ASTRAL version 5.7.8
Gene trees are treated as unrooted
Exception in thread "main" java.lang.RuntimeException: Empty name observed; likely, an input tree has an error
        at phylonet.coalescent.TaxonIdentifier.taxonId(TaxonIdentifier.java:33)
        at phylonet.coalescent.CommandLine.readInputTrees(CommandLine.java:797)
        at phylonet.coalescent.CommandLine.readOptions(CommandLine.java:321)
        at phylonet.coalescent.CommandLine.main(CommandLine.java:486)

What is the reason for this and how can I resolve it.

Many thanks, 
Upendra

**Comment by biocyberman** [comment]
You probably were running with multi-alignment file, not a tree file. You need to generate a tree with `raxml-ng` or something before you run `ASTRAL` with the tree.
