### ISSUE TITLE
Error message regarding gene trees input file format

### ISSUE THREAD

**Issue by abcbot123** [smirarab/ASTRAL#94]
Hi,
I'm using ASTRAL tool to get the species tree using gene trees. I have created the gene trees and the bootstrap gene trees using RAxML. This is the code I have used in ASTRAL.
java -jar Astral/astral.5.7.1.jar -i genetree_combine -o astral_speciestree -b bootstrap_combine -r 100

This is the error I got,
================== ASTRAL ===================== 

This is ASTRAL version 5.7.1
Gene trees are treated as unrooted
Exception in thread "main" java.lang.RuntimeException: Failed to Parse Tree number: 1
	at phylonet.coalescent.CommandLine.readInputTrees(CommandLine.java:835)
	at phylonet.coalescent.CommandLine.readOptions(CommandLine.java:328)
	at phylonet.coalescent.CommandLine.main(CommandLine.java:513)
Caused by: phylonet.tree.io.ParseException: ')' expected
	at phylonet.tree.io.NewickReader.readNode(NewickReader.java:405)
	at phylonet.tree.io.NewickReader.readNode(NewickReader.java:399)
	at phylonet.tree.io.NewickReader.readNode(NewickReader.java:399)
	at phylonet.tree.io.NewickReader.readNode(NewickReader.java:399)
	at phylonet.tree.io.NewickReader.readNode(NewickReader.java:399)
	at phylonet.tree.io.NewickReader.readNode(NewickReader.java:399)
	at phylonet.tree.io.NewickReader.readNode(NewickReader.java:399)
	at phylonet.tree.io.NewickReader.readTree(NewickReader.java:374)
	at phylonet.tree.io.NewickReader.readTree(NewickReader.java:95)
	at phylonet.coalescent.CommandLine.readInputTrees(CommandLine.java:802)
	... 2 more
Is this error regarding my input file format?
But I couldn't figure out any format errors in my input files. I have look for the test_data in the tool itself and seems my data is in the same Newick format. Could you please help me to figure out what's the formatting error in my input files.

Thanks so much!

**Comment by biocyberman** [comment]
I got the same error and figured out that it is because I have '/' characters in the identifiers of the entries in the newick tree files. After replacing them with `_`, it works. @smirarab

**Comment by smirarab** [comment]
It's hard for me to know what is going wrong without seeing the input. It may be an unsupported character, as @biocyberman mentioned. But it also could be the format of the `bootstrap_combine` files is wrong. Please see <https://github.com/smirarab/ASTRAL/blob/master/astral-tutorial.md#multi-locus-bootstrapping> Make sure you `-b` file inclues the path to newick files, as mentioned in the tutorial.

**Comment by SheevP** [comment]
Same error report when I using the "-q" paramater to score my tree.
Here is my command:
java -Xmx1000M -jar /home/phylogenetic_package/Astral/astral.5.7.4.jar \
         -i test.tre \
        -q result_speciestree.tre \
        -o result_speciestree.scored.tre \
        -a species_list.txt \
